### ISSUE TITLE
Error: `Invalid continuation byte` with Russian (windows-1251 charset) text

### ISSUE THREAD

**Issue by mariozaizar** [mathiasbynens/quoted-printable#5]
Hi, I'm getting `Invalid continuation byte` error when I tried to decode some Russian text.

```javascript
$ quoted-printable --decode '=CA=EE=EB=EB=E5=E3=E8, =EF=F0=E8=E2=E5=F2!'
Invalid continuation byte

Error: failed to decode.
If you think this is a bug in quoted-printable, please report it:
https://github.com/mathiasbynens/quoted-printable/issues/new

Stack trace using quoted-printable@1.0.1:

Error: Invalid continuation byte
    at readContinuationByte (~/test/node_modules/utf8/utf8.js:131:9)
    at decodeSymbol (~/test/node_modules/utf8/utf8.js:160:12)
    at Object.utf8decode [as decode] (~/test/node_modules/utf8/utf8.js:206:17)
    at ~/test/node_modules/quoted-printable/bin/quoted-printable:64:20
    at Array.forEach (native)
    at main (~/test/node_modules/quoted-printable/bin/quoted-printable:43:11)
    at ~/test/node_modules/quoted-printable/bin/quoted-printable:90:3
    at Object.<anonymous> (~/test/node_modules/quoted-printable/bin/quoted-printable:116:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

The expected decoded text should be `Коллеги, привет!` (translates to "Colleagues, hello!").
I was able to decode it using http://www.webatic.com/run/convert/qp.php

> ![screen shot 2017-04-18 at 11 05 54 am](https://cloud.githubusercontent.com/assets/164819/25145862/056ba506-2427-11e7-8891-390b744be40c.png)

_Full example:_
```
=CA=EE=EB=EB=E5=E3=E8, =EF=F0=E8=E2=E5=F2!
=CF=F0=EE=F8=F3 =EE=E1=EE=F0=F3=E4=EE=E2=E0=F2=FC =EC=EE=E5 =F0=E0=E1=EE=F7=
=E5=E5 =EC=E5=F1=F2=EE =C8=C1=CF.
=D1=EF=E0=F1=E8=E1=EE.
```

**Comment by mathiasbynens** [comment]
The error is coming from utf8.js.

Where did you get the string that you’re trying to decode? Did you encode it yourself somehow?

When I [encode `Коллеги, привет!`](https://mothereff.in/quoted-printable#%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%B3%D0%B8%2C%20%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82!), I get:

```
=D0=9A=D0=BE=D0=BB=D0=BB=D0=B5=D0=B3=D0=B8, =D0=BF=D1=80=D0=B8=D0=B2=D0=B5=
=D1=82!
```

Decoding that works fine.

**Comment by mariozaizar** [comment]
From an email body (raw .eml file) (presumably MS Exchange or Windows Mail client).

**Comment by mathiasbynens** [comment]
What do the mail headers say? The string you posted (`=CA=EE=EB=EB=E5=E3=E8, =EF=F0=E8=E2=E5=F2!`) looks a little short to be that Russian text in UTF-8.

**Comment by mariozaizar** [comment]
Nothing much in the email headers/body:
```html
Subject: =?windows-1251?B?yMHP?=
Accept-Language: en-US
Content-Language: ru-RU
--_000_991b4223462f43de8d26145fa3f82b25mclust2depolocal_
Content-Type: text/plain; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable

=CA=EE=EB=EB=E5=E3=E8, =EF=F0=E8=E2=E5=F2!
=CF=F0=EE=F8=F3 =EE=E1=EE=F0=F3=E4=EE=E2=E0=F2=FC =EC=EE=E5 =F0=E0=E1=EE=F7=
=E5=E5 =EC=E5=F1=F2=EE =C8=C1=CF.
=D1=EF=E0=F1=E8=E1=EE.

--_000_991b4223462f43de8d26145fa3f82b25mclust2depolocal_
Content-Type: text/html; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dwindows-1=
251">
<meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
<style><!--
/* Font Definitions */
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:#0563C1;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:#954F72;
	text-decoration:underline;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang=3D"RU" link=3D"#0563C1" vlink=3D"#954F72">
<div class=3D"WordSection1">
<p class=3D"MsoNormal">=CA=EE=EB=EB=E5=E3=E8, =EF=F0=E8=E2=E5=F2!<o:p></o:p=
></p>
<p class=3D"MsoNormal">=CF=F0=EE=F8=F3 =EE=E1=EE=F0=F3=E4=EE=E2=E0=F2=FC =
=EC=EE=E5 =F0=E0=E1=EE=F7=E5=E5 =EC=E5=F1=F2=EE =C8=C1=CF.<o:p></o:p></p>
<p class=3D"MsoNormal">=D1=EF=E0=F1=E8=E1=EE.<o:p></o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>
```

Did you saw the _full example_ string I posted at the end? 
The translation looks fine to me (what do you mean by too short to be Russian?)

**Comment by mathiasbynens** [comment]
> what do you mean by too short to be Russian?

The [UTF-8-encoded version of `Коллеги, привет!`](https://mothereff.in/utf-8#%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%B3%D0%B8%2C%20%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82!) is:

```
\xD0\x9A\xD0\xBE\xD0\xBB\xD0\xBB\xD0\xB5\xD0\xB3\xD0\xB8\x2C\x20\xD0\xBF\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82\x21
```

The encoded text you posted is different and much shorter — it doesn’t seem to be the string’s UTF-8 encoding.

The mail headers confirm this:

```
Content-Type: text/html; charset="windows-1251"
```

The encoding used is `windows-1251`. To decode this, you could follow https://github.com/mathiasbynens/quoted-printable#quotedprintabledecodetext but instead of using utf8.js, you’d use https://github.com/mathiasbynens/windows-1251.
